checks:
  php: true

build:
  environment:
    php: 7.2.13
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]
      cache:
        directories:
          - vendor/
filter:
  paths: ["src/*"]

tools:
  external_code_coverage: true
