# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 586f7041e9f71c44946cdfe8bce27d66c6271d173ec291c2a9aa7e1b56667873
    docker:
      - image: ssmarco/php-solr:latest
        environment:
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=test
          - SS_DEFAULT_ADMIN_USERNAME=admin
          - SS_DEFAULT_ADMIN_PASSWORD=password
          - DEBUGBAR_DISABLE=true
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: /var/www/html

    steps:
      - run: cd /var/www/html
      - checkout
      - run: touch composer.lock # Create an empty lockfile
      - run: echo '{}' > composer.lock
      - restore_cache:
          keys:
            - silverstripe-search-cache-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - silverstripe-search-cache-
      - run: composer require silverstripe/recipe-cms
      - save_cache:
          key: silverstripe-search-cache-{{ checksum "composer.lock" }}
          paths:
            # fallback to using the latest cache if no exact match is found
            - vendor
            - app
      - run: composer update -n --prefer-dist --ignore-platform-reqs
      - run: composer vendor-expose
      - run:
          name: Setup Integration Pre-requisites
          command: |
            cp .circleci/.env.test ./.env
            cp .circleci/CircleCITestIndex.phpsrc app/src/CircleCITestIndex.php
            cp .circleci/Subsite.phpsrc app/src/Subsite.php
            cp .circlecy/TestIndexTwo.yml app/_config/search.yml
      - run: vendor/bin/sake dev/build flush=all skipannotation=true
      - run:
          name: Run Solr Configure
          command: |
            service apache2 restart
            service solr restart
            mkdir -p /var/www/html/.solr && chmod -R 777 /var/www/html/.solr
            chown -R solr:solr /var/www/html/.solr
            su solr vendor/bin/sake dev/tasks/SolrConfigureTask
      - run:
          name: Check Solr Core - CircleCITestIndex is successfully created
          command: |
            RESPONSE=$(echo $(curl -I http://localhost:8983/solr/CircleCITestIndex/admin/ping | head -n1 ) | grep -o '200 OK')
            if [[ $RESPONSE != '200 OK' ]]; then echo "Solr Core - CircleCITestIndex is not created"; fi
            echo "CircleCITestIndex is successfully created"
      - run: su solr vendor/bin/sake dev/tasks/SolrIndexTask
      - run:
          name: Check Solr has successfully indexed the default 5 pages
          command: |
            wget http://localhost:8983/solr/CircleCITestIndex/update?commit=true
            RESPONSE=$(echo $(curl http://localhost:8983/solr/CircleCITestIndex/select?q=*) | grep -o '"numFound":5')
            if [[ -z "$RESPONSE" ]]; then echo "No indexed documents"; exit 1; fi
            echo "Solr has successfully indexed documents"
      - run:
          name: Permission changes and testing
          command: |
            usermod -a -G www-data solr
            groups solr
            usermod -a -G solr www-data
            groups www-data
            chown -R solr:www-data /var/www/html
            chmod -R u+rwxs,g+rwxs /var/www/html
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
            set +e
            su solr -s $SHELL -c 'vendor/bin/phpunit --coverage-clover=clover.xml --log-junit ./coverage/junit.xml -d memory_limit=512M tests/unit'
      - run:
          name: Code coverage reportes
          command: |
            wget https://scrutinizer-ci.com/ocular.phar
            php ocular.phar code-coverage:upload --format=php-clover clover.xml
            bash <(curl -s https://codecov.io/bash) -f clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      - run: vendor/bin/phpcs --standard=phpcs.xml.dist src
      - store_test_results:
          path: /var/www/html/coverage
      - store_artifacts:
          path: /var/www/html/coverage
          destination: phpunit
